name: porthole
dependencies:
  - python=3.6
  - pymysql
  - psycopg2
  - xlsxwriter
  - openpyxl=2.6.2  #this library allows for editing of existing Excel files
  - lxml            #this library speeds up openpyxl
  - SQLAlchemy
  - pytz

